# Generated by Django 5.0.6 on 2024-06-30 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('URL_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'APP_album',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('URL_image', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('fileName', models.CharField(max_length=255)),
                ('URL_music', models.CharField(max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='APP.album')),
            ],
            options={
                'db_table': 'APP_songs',
            },
        ),
    ]
